### ISSUE TITLE
unable to run pubsub

### ISSUE THREAD

**Issue by naturzukunft** [hbz/skohub-pubsub#64]
i ried starting it like:
```
$ git clone https://github.com/skohub-io/skohub-pubsub.git
$ cd skohub-pubsub
$ npm install
$ npm test
$ PORT=3000 npm start
```

but get the following error:

```
$ PORT=3000 npm start

> skohub-pubsub@0.1.0 start
> node index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'uuid'
Require stack:
- /home/fredy/git/skohub-pubsub/src/activitypub.js
- /home/fredy/git/skohub-pubsub/src/server.js
- /home/fredy/git/skohub-pubsub/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fredy/git/skohub-pubsub/src/activitypub.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/fredy/git/skohub-pubsub/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/fredy/git/skohub-pubsub/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fredy/git/skohub-pubsub/src/server.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/fredy/git/skohub-pubsub/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/fredy/git/skohub-pubsub/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fredy/git/skohub-pubsub/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/fredy/git/skohub-pubsub/src/activitypub.js',
    '/home/fredy/git/skohub-pubsub/src/server.js',
    '/home/fredy/git/skohub-pubsub/index.js'
  ]
}


```

**Comment by naturzukunft** [comment]
```
$ npm test

> skohub-pubsub@0.1.0 test
> eslint src/ && jest --forceExit

/home/fredy/git/skohub-pubsub/node_modules/jest-cli/build/run.js:135
    if (error?.stack) {
              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fredy/git/skohub-pubsub/node_modules/jest-cli/build/index.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by acka47** [comment]
We announced on 2022-03-01 that we do not have the resources to bring SkoHub PubSub further, see the [blog post](https://blog.skohub.io/2020-06-25-skohub-pubsub/) (Unfortunately, we  did not mention this in the repo itself and should add it.) Basically, nothing has changed since then as we have focused on consolidating SkoHub Vocabs and bringing [SkoHub reconcile](https://github.com/skohub-io/skohub-reconcile) further towards production. This repo was last touched in 2021 and we have no concrete plans to pick up development. What kept us from taking this on again was mainly the lack of a concrete use case, especially in the educational/higher ed space. If you have such a use case, we might be able to help out a bit with the development.

Generally, we would probably completely rewrite SkoHub PubSub by now as it was built from scratch by @literarymachine in 2019 and since then [a lot of ActivityPub development resources](https://codeberg.org/fediverse/delightful-activitypub-development) started to exist we could now built on.

**Comment by naturzukunft** [comment]
ok, good to know. maybe also a usecase for https://rdfpub.org

**Comment by acka47** [comment]
We would like to test out [Emissary](https://emissary.dev/) for setting up a SkoHub PubSub instance. I got aware of Emissary trhough this recent wedistribute post: https://wedistribute.org/2024/04/emissary-social-web/ As @sroertgen will be on parental leave coming next week, it probably won't happen soon, though.

I guess we can close this issue then?
